### ISSUE TITLE
S3_IRSA Dynamo/KMS access issue

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/iac#111]
When standing up an S3 bucket for Loki using the s3_irsa module, I recieved this notification from AWS:

Dear AWS customer,

On Mon Mar 20 11:20:46 UTC 2023, the Amazon DynamoDB service detected that it does not have access to your table that was encrypted with a customer-managed customer master key (CMK) in your AWS account XXXXXXXXX. DynamoDB must have access to your encryption key to ensure you can continue accessing your table and to prevent any data loss. The following table is currently “inaccessible”:

Table name: tommy-bigbang-dynamodb_index
Region: US West (Oregon) us-west-2
Table encryption key: arn:aws:kms:us-west-2:XXXXXXX:key/e8479c67-bc1d-470f-ba7b-a2bf1ba890f3

To ensure that you can continue working with the table, you must provide DynamoDB access to the specified encryption key. You can do this by re-enabling the encryption key, canceling the pending delete action, re-importing the key material or re-creating the grant (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/encryption.usagenotes.html). You can choose to delete your table if you no longer want to access your table data.   

If DynamoDB cannot access your encryption key for longer than 7 days since detection, the table will be “Archived” and can no longer be accessed. DynamoDB will automatically create an on-demand backup of your table, and you will be billed for it (https://aws.amazon.com/dynamodb/pricing/). You can use the on-demand backup to restore to a new table. To learn more, see (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/EncryptionAtRest.html)

Sincerely,
The Amazon DynamoDB Team

Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210

**Comment by ntwkninja** [comment]
We plan to use the internal boltdb-shipper for indexing and deprecate the dynamodb index. [PR to close this issue](https://github.com/defenseunicorns/iac/pull/117) if you are good with it.

"boltdb-shipper helps run Loki with one less dependency and also saves costs in storage since object stores are likely to be much cheaper compared to cost of a hosted NoSQL store or running a self hosted instance of Cassandra"

https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/

https://github.com/grafana/loki/issues/2801#issuecomment-1197193440
https://github.com/grafana/loki/issues/4957#issue-1083183709
