### ISSUE TITLE
Add Testing pipeline for PRs

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/iac#14]
Looking at 
- [terratest](https://github.com/gruntwork-io/terratest) allows you to write automated tests for your templates
- [terraform-testing](https://github.com/antonbabenko/terraform-testing)

**Comment by ntwkninja** [comment]
rated as pri 3 as we iterate quickly and test manually... but this should really have a testing pipeline

**Comment by RothAndrew** [comment]
Created #44 to specifically focus on linting and other quality gate stuff, so this issue can just deal with the beginnings of having an automated testing suite for the terraform modules that we are creating.

**Comment by RothAndrew** [comment]
This will be valuable to work ASAP. I'm currently going through the instructions for deploying the complete-self-managed-nodegroup example. It's ~25 steps or so?

Doing what I'm doing right now manually could easily turn into

```
# Deploy
export SKIP_TEARDOWN=1
make test

# Everything's deployed, do whatever you want
kubectl get nodes

# Now teardown
unset SKIP_TEARDOWN
export SKIP_SETUP=1
export SKIP_TEST=1
make test
```

Plus, we'll get real tests that we can run in PRs or on main that stands up the entire environment and automatically tears it down

**Comment by RothAndrew** [comment]
Examples of this pattern being used:

* https://github.com/defenseunicorns/zarf-package-software-factory/tree/main/test/e2e
* https://github.com/defenseunicorns/terraform-aws-tfstate-backend/tree/main/test/e2e

**Comment by RothAndrew** [comment]
@ntwkninja how would you feel about me working this instead of #75?

**Comment by RothAndrew** [comment]
Initial design:

* Create a new example called `complete-insecure`
* Set up a Terratest test for it
* Set up GitHub Actions so that the test will run whenever someone comments `/test e2e` or `/test all` in a PR, plus always run on pushes to `main`

Future iteration:

* Update examples `complete-managed-nodegroup` and `complete-self-managed-nodegroup` to
	* `complete-insecure` -- Uses managed nodegroups, default tenancy, and cluster endpoint public access enabled
	* `complete-secure` -- Uses self-managed nodegroups, dedicated tenancy, and cluster endpoint public access disabled

**Comment by RothAndrew** [comment]
cc @zack-is-cool since you've been working closely on this stuff recently

**Comment by RothAndrew** [comment]
Actually I think we could just have the same folder with two different tfvars files: `complete-insecure.tfvars` and `complete-secure.tfvars`

**Comment by zack-is-cool** [comment]
They are basically the same, the only real difference is with the `main.yaml` files and the `self_managed_node_groups` and `managed_node_groups` blocks.

I feel like if we wanted to keep it all condensed into a single TF module we could add logic like:

- Add 2 different variables that will act as boolean switches for each of the `self_managed_node_groups` and `managed_node_groups` configuration blocks.
  - ex: input var of `deploy_self_managed_node_groups` = false -> use `try` pattern to ignore maps under `self_managed_node_groups` using the [`create` input](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L382).

Obviously this makes our examples a little more dense, but maybe a good trade off for having a single "`complete`" example? 

What do you think about terraform testing and state? With Terratest we would probably just use local state since everything would be getting torn down after?

**Comment by RothAndrew** [comment]
yes, in terratest just local state

**Comment by RothAndrew** [comment]
This is working so far with my experimentation. Not trying to incorporate this into the actual eks module right now, just updating the example's main.tf

![image](https://user-images.githubusercontent.com/16000938/222281663-3ce0273b-f7bf-4aa9-9c4e-c2aab0db117e.png)

**Comment by RothAndrew** [comment]
Currently working on an idea to have a `common.tfvars`, then a `insecure.tfvars` and `secure.tfvars` with just the couple of differences

![image](https://user-images.githubusercontent.com/16000938/222281899-f4ac4d54-1899-4e9c-b21c-ba8205ca2279.png)

**Comment by RothAndrew** [comment]
But I definitely do think we could incorporate this into the actual EKS module, where all we do is have variables `enable_managed_nodegroups` (`bool`) and `node_groups` (`map(any)`)

**Comment by RothAndrew** [comment]
PR for this is ready for review/merge
