### ISSUE TITLE
Ensure we are supporting K8s NetPols

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/iac#75]
By default, EKS ships with it's own VPC-CNI, but it currently [doesn't support K8s NetworkPolicy resources](https://github.com/aws/containers-roadmap/issues/1478). For this EKS module, let's make sure that K8s NetPols can be implemented and enforced. This [Github issue](https://github.com/aws/amazon-vpc-cni-k8s/issues/1257#issuecomment-706408142) recommends Calico or Security Groups for Pods, but each of those comes with its own pros/cons.

**Comment by ntwkninja** [comment]
Request we include VPC CNI Custom Networking into this feature since it is needed in IP constrained environments and creates a clear separation of public facing resources like ELBs / Ingress Gateways and pods within the cluster that should not be exposed.

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/vpc-cni-custom-networking
https://aws.github.io/aws-eks-best-practices/networking/custom-networking/#use-custom-networking-when

Not sure if this [beta plugin](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/README.md) is related

**Comment by RothAndrew** [comment]
Unassigning since I don't plan on working on this today and I'll be out the next few days. Will pick it back up when I am ready to work it.

**Comment by ntwkninja** [comment]
https://aws.amazon.com/blogs/containers/introducing-security-groups-for-pods/

**Comment by ntwkninja** [comment]
https://aws.github.io/aws-eks-best-practices/security/docs/network/

https://aws.github.io/aws-eks-best-practices/networking/custom-networking/

**Comment by RothAndrew** [comment]
@ntwkninja what's the status on this?
